
#get all products
GET http://localhost:1337/api/products?populate=*

###
#get single product
GET http://localhost:1337/api/products/1?populate=*

###

GET http://localhost:1337/api/uploads/pride_af176d2ba4.jpg

###

POST http://localhost:1337/api/auth/local
Content-Type: application/json

{
    "identifier": "mihaela@example.com",
    "password": "Havefun1!"
}

###

GET http://localhost:1337/api/cart-items?populate=*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwMDI0ODIyLCJleHAiOjE2ODI2MTY4MjJ9.DnLbKQCWImMZrV3KbHMCiTDs50bFag0Umwp9ujFzYGM


###

GET http://localhost:1337/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjc5Njk1NjA2LCJleHAiOjE2ODIyODc2MDZ9.CLTSGnuWGIwhgkRmqLnmxcXeHFQcKgTEh9pdsTvVGlE

###

POST http://localhost:1337/api/auth/local/register
Content-Type: application/json

{
    "username": "Mihai",
    "identifier": "mihai@example.com",
    "password": "Havefun1!"
}

###

GET http://localhost:3000/api/login

####
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "mihaela@example.com",
    "password": "Havefun1!"
}